### PR TITLE
Added Backend README File

### PR DESCRIPTION
**Pull request by Kelbaso**
Added Backend README file as per requested through the Peer Review Feedback Forms.

### CODE REVIEW

**Comment by Kelbaso** [comment]
Added new documentation as per the peer review process.

**Review by lochoa2 — COMMENTED** [review]
Clear and detailed Readme file

**Comment by slok1368** [comment]
LGTM!

**Review by slok1368 — APPROVED** [review]

**Review by asagrekin — APPROVED** [review]
Looks good, I don't see any grammar errors or anything.

**Pull request merged**
